---

- name: ensures {{ dst_install_dir }}bin/ directory exists
  file:
    path: '{{ dst_install_dir }}bin/'
    state: directory
    recurse: yes

- name: create update script
  template:
    src: update.j2
    dest: '{{ dst_install_dir }}bin/update'
    mode: 0755

- name: install or update app
  shell: "{{ steamcmd_directory }}steamcmd.sh +runscript {{ dst_install_dir }}bin/update > /tmp/output.stdout 2> /tmp/output.stderr"
  async: 180
  poll: 5
  register: app_update
