---
- include_vars: '../../../sensitive_ansible/inventory/host_vars/{{ dontstarvetogether_server }}.yml'
- include: requirements.yml
- include: packages.yml
- include: app.yml
  become: yes
  become_user: '{{ steamcmd_user }}'
- include: server.yml
  become: yes
- include: '../../tasks/adjust_files.yml'
  become: yes
- include: '../../tasks/create_files.yml'
  become: yes
- include: '../../tasks/install_files.yml'
  become: yes
- include: '../../tasks/symlinks.yml'
  become: yes
- include: service.yml
  when: dst_server_as_a_service
