---

- name: add i386 architecture onto Debian family
  command: dpkg --add-architecture i386
  when: ansible_os_family == 'Debian'

- name: update the apt package index
  apt: update_cache=yes
  when: ansible_pkg_mgr == 'apt'

- name: install the dependencies required to run a Don't Starve Together server
  package: name={{ item }} state=present
  with_items:
    - lib32gcc1
    - lib32stdc++6
    - libcurl4-gnutls-dev:i386
    - screen

