---

- name: copy server init script into place
  template:
    src: server/bin/start.j2
    dest: /etc/init.d/dst-{{ dst_shard_name }}
    owner: steam
    group: steam
    mode: 0755

- name: ensure the server is enabled and will start on boot
  service:
    name: dst-{{ dst_shard_name }}
    state: started
    enabled: yes
