---

- name: ensures that server directory `{{ steamcmd_user_home }}.klei/{{ dst_shard_name }}/` exists
  file:
    path: '{{ steamcmd_user_home }}.klei/{{ dst_shard_name }}/'
    state: directory

- name: creates settings file cluster.ini
  template:
    src: server/cluster.ini.j2
    dest: '{{ steamcmd_user_home }}.klei/{{ dst_shard_name }}/cluster.ini'

- name: creates settings file server.ini
  template:
    src: server/server.ini.j2
    dest: '{{ steamcmd_user_home }}.klei/{{ dst_shard_name }}/server.ini'

- name: creates server token file
  template:
    src: server/cluster_token.txt.j2
    dest: '{{ steamcmd_user_home }}.klei/{{ dst_shard_name }}/cluster_token.txt'

- name: creates world generation file.
  template:
    src: server/worldgenoverride.lua.j2
    dest: '{{ steamcmd_user_home }}.klei/{{ dst_shard_name }}/worldgenoverride.lua'
