---

- name: ensures that server directory `{{ steamcmd_user_home }}.klei/{{ dst_shard_name }}/` exists
  file:
    path: '{{ steamcmd_user_home }}.klei/{{ dst_shard_name }}/'
    state: directory

- name: creates settings file
  template:
    src: server/settings.ini.j2
    dest: '{{ steamcmd_user_home }}.klei/{{ dst_shard_name }}/settings.ini'

- name: creates server token file
  template:
    src: server/server_token.txt.j2
    dest: '{{ steamcmd_user_home }}.klei/{{ dst_shard_name }}/server_token.txt'

- name: creates world generation file.
  template:
    src: server/worldgenoverride.lua.j2
    dest: '{{ steamcmd_user_home }}.klei/{{ dst_shard_name }}/worldgenoverride.lua'
